### ISSUE TITLE
When user has no access to this app, it loads forever

### ISSUE THREAD

**Issue by rvsia** [RedHatInsights/approval-ui#64]
error: `message: "Current role cannot access /api/approval/v1.0/requests"`

![image](https://user-images.githubusercontent.com/32869456/65419700-8b00df80-ddff-11e9-8b68-126eced6db6c.png)

It would be nice to show some human readable message and stop the loading.

**Comment by lgalis** [comment]
@rvsia - thank you. There are new rbac APIs for the Approval that will replace the current ones. UX will work on screens for what the user will be presented with when there is no access - these are WIP.

**Comment by rvsia** [comment]
@lgalis Great! Thanks for quick response!

**Comment by rvsia** [comment]
I believe this is solved already
